name: GitHub Actions Demo
on: [push]
env:
  DOG: yes
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: | 
          ls ${{ github.workspace }}
      - name: e1
        run: env
        env:
          SHIMON: 1
      - name: e2
        run: env
        env:
          NILS: 1

      - name: pwd
        run: echo ${{ pwd }}