# name: CloudQuery
# on: [push]

# jobs:
#   cloudquery:
#     permissions:
#       id-token: write
#       contents: read
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3 # Checkout the code so we have access to the config file
#       - name: Configure AWS credentials # Setup AWS credentials (example)
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           role-to-assume: arn:aws:iam::615713231484:role/shimon-oidc-readonly-role # based on the role you created in the pre-requisites
#           aws-region: eu-west-3 # based on the region you created the role in
#       - uses: cloudquery/setup-cloudquery@v2
#         name: Setup CloudQuery
#       - name: Sync with CloudQuery
#         run: cloudquery sync cloudquery.yml --log-console
#         env:
#           CQ_DSN: ${{ secrets.CQ_DSN }} # Connection string to a PostgreSQL database
