name: GitHub Actions Demo
on: [push]
env:
  DOG: yes
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::615713231484:role/shimon-oidc-readonly-role
          role-session-name: samplerolesession
          aws-region: eu-west-3
      - uses: cloudquery/setup-cloudquery@v2
        name: Setup CloudQuery
      - name: Sync with CloudQuery
        run: cloudquery sync cloudquery.yml --log-console
        env:
          CQ_DSN: ${{ secrets.CQ_DSN }} # Connection string to a PostgreSQL database
          #CQ_DSN: "postgres://postgres:pass@postgres:5432/postgres?sslmode=disable"
      - name: List files in the repository
        run: | 
          ls ${{ github.workspace }}
      - name: List vpcs
        run: |
          aws ec2 describe-vpcs --region eu-west-3